In [60]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [61]:
#Type data 2.20.1

import numpy as np
a_29 = np.array([2,4,6,8,10])
print(a_29)

b_29 = np.array([[[1,2,3,4],[5,6,7,8]],
              [[-4,-3,-2,-1],[1,-2,-6,0]],
              [[1,0,1,0],[2,1,2,5]]])
print(b_29)
print(a_29.ndim)
print(b_29.ndim)
print(a_29.shape)
print(b_29.shape)

[ 2  4  6  8 10]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[-4 -3 -2 -1]
  [ 1 -2 -6  0]]

 [[ 1  0  1  0]
  [ 2  1  2  5]]]
1
3
(5,)
(3, 2, 4)


In [62]:
#Type 2.20.2

import numpy as np
b_29 =  np.array([[1,2,3,4,5],[2,4,6,8,10],[1,3,5,7,9]])
print(b_29)
print((b_29) [1])
print((b_29) [2][1])
print((b_29) [1,4:2])

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 1  3  5  7  9]]
[ 2  4  6  8 10]
3
[]


In [63]:
#Type data 2.20.3

import numpy as np
a_29 = np.ones((10,10))
print(a_29)
b_29 = np.identity(4)
print(b_29)
c_29 = 3*b_29
print(c_29)
d_29 = np.ones((2,1))
e_29 = np.identity(2)*2
f_29 = d_29+e_29
print(f_29)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[3. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 3.]]
[[3. 1.]
 [1. 3.]]


In [64]:
#Type data 2.20.4

import numpy as np

print("pada saat belajar mengenai matriks kami disuruh untuk mnejabarkan matriks yang telah di berikan" )

matriks_A_29 = np.array([[1,2,3,4],
                      [7,8,9,10],
                      [2,4,6,8]])
matriks_B_29 = np.array([[9,8,7],
                      [5,4,3],
                      [-4,-3,-2],
                      [3,6,7]])
matriks_C_29 = matriks_B_29.copy ()
print(matriks_C_29)
matriks_A_29[1] = 8
print(matriks_A_29)


pada saat belajar mengenai matriks kami disuruh untuk mnejabarkan matriks yang telah di berikan
[[ 9  8  7]
 [ 5  4  3]
 [-4 -3 -2]
 [ 3  6  7]]
[[1 2 3 4]
 [8 8 8 8]
 [2 4 6 8]]


In [65]:
#Type 2.20.5

import numpy as np

print("Tentukan hasil dari matriks yang ada di bawah ini!")

matriks_X_29 = np.array([[-1,2,-3,4],
                      [0,7,1,2],
                      [9,3,7,5]])
matriks_Y_29 = np.array([[8,2,4,6],
                      [4,5,3,1],
                      [12,4,3,6],
                      [2,0,1,3]])
matriks_Z_29 = np.array([[5,3,2,7],
                      [3,9,1,2],
                      [11,3,2,5]])
print( matriks_X_29+2)
print(matriks_Y_29*3)
print(matriks_Z_29**2)
print(matriks_X_29-matriks_Z_29)
print(np.cos(matriks_X_29))
print(np.sinh(matriks_X_29))
print(np.tan(matriks_Z_29))



Tentukan hasil dari matriks yang ada di bawah ini!
[[ 1  4 -1  6]
 [ 2  9  3  4]
 [11  5  9  7]]
[[24  6 12 18]
 [12 15  9  3]
 [36 12  9 18]
 [ 6  0  3  9]]
[[ 25   9   4  49]
 [  9  81   1   4]
 [121   9   4  25]]
[[-6 -1 -5 -3]
 [-3 -2  0  0]
 [-2  0  5  0]]
[[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [ 1.          0.75390225  0.54030231 -0.41614684]
 [-0.91113026 -0.9899925   0.75390225  0.28366219]]
[[-1.17520119e+00  3.62686041e+00 -1.00178749e+01  2.72899172e+01]
 [ 0.00000000e+00  5.48316123e+02  1.17520119e+00  3.62686041e+00]
 [ 4.05154190e+03  1.00178749e+01  5.48316123e+02  7.42032106e+01]]
[[-3.38051501e+00 -1.42546543e-01 -2.18503986e+00  8.71447983e-01]
 [-1.42546543e-01 -4.52315659e-01  1.55740772e+00 -2.18503986e+00]
 [-2.25950846e+02 -1.42546543e-01 -2.18503986e+00 -3.38051501e+00]]


In [66]:
#Type 2.20.6

print("pada saat belajar mengenai matriks kami disuruh untuk mengrejakan perkalian matriks" )

matriks_A_29 = np.array([[1,2,3,4],
                      [7,8,9,10],
                      [2,4,6,8]])
matriks_B_29 = np.array([[9,8,7],
                      [5,4,3],
                      [-4,-3,-2],
                      [3,6,7]])
#matriks_C_29 = matriks_A*matriks_B_29
print(matriks_B_29)
#matriks_E_29 = matriks_B_29*matriks_A_29
#print(matriks_E_29)
hasil = np.matmul(matriks_A_29,matriks_B_29)
print(hasil)


pada saat belajar mengenai matriks kami disuruh untuk mengrejakan perkalian matriks
[[ 9  8  7]
 [ 5  4  3]
 [-4 -3 -2]
 [ 3  6  7]]
[[ 19  31  35]
 [ 97 121 125]
 [ 38  62  70]]


In [67]:
#Type data 2.20.7
print("Tentukan nilai maksimum dan minimum dari suatu matriks berikut!")
P_29 = np.array([[5,4,3,1],
              [-1,4,-2,5],
              [0,1,2,3]])
print(P_29)
Q_29 = np.min(P_29)
print(Q_29)
R_29 = np.min(P_29,axis=0)
print(R_29)
S_29 = np.max(P_29)
print(S)
T_29 = np.max(P_29,axis=1)
print(T_29)

Tentukan nilai maksimum dan minimum dari suatu matriks berikut!
[[ 5  4  3  1]
 [-1  4 -2  5]
 [ 0  1  2  3]]
-2
[-1  1 -2  1]
5
[5 5 3]
